name: build-and-push-to-my-portainer
on:
  push:
    branches:
      - main
env:
  PORTAINER_URL: "portainer.astrolab-agency.com"
  PORTAINER_REGISTRY_USERNAME: ${{ secrets.USERNAME }}
  PORTAINER_REGISTRY_PASSWORD: ${{ secrets.PORTAINER_REGISTRY_PASSWORD }}
  REGISTRY_HTTP_RELATIVEURLS: "true"
  OPENSANCTIONS_DATABASE_URI: "postgresql://opensanctions:opensanctions@localhost/opensanctions"
  OPENSANCTIONS_RESOLVER_PATH: /dev/null
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}
      - name: Build docker image 
        run: |
          docker-compose build 
          docker-compose up 
          docker push ghcr.io/astrolabagency/opensanctions:latest 
          docker-compose down 
      - name: login &pull images into portainer 
        run: |
         echo "${{ env.PORTAINER_REGISTRY_PASSWORD }}" | docker login --username "${{ env.PORTAINER_REGISTRY_USERNAME }}" --password-stdin portainer.astrolab-agency.com  
         docker  pull <ghcr.io/astrolabagency/opensanctions:latest>
         docker push  portainer.astrolab-agency.com/opensanctions:latest


  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: opensanctions
          POSTGRES_USER: opensanctions
          POSTGRES_DB: opensanctions
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
 
    
 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install -y -qq libicu-dev
          pip install --no-cache-dir -q -e ".[dev]"
          pip freeze
      - name: Crawl a single dataset
        run: |
          opensanctions crawl us_ofac_cons
      - name: Export a single dataset
        run: |
          opensanctions export us_ofac_cons
      - name: Build analytics data
        run: |
          opensanctions build-analytics
      - name: Clear all data
        run: |
          opensanctions clear-workdir all
      - name: Build a distribution
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish opensanctions to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          packages_dir: dist/
          skip_existing: true
 