# The point of this job is to re-build docker base images once a day so
# that upstream package updates are reflected and dependency security
# vulns don't become an issue.
name: docker

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  docker:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
   steps:
      - uses: actions/checkout@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}
      - name: Build docker image 
        run: |
          docker build . --tag ghcr.io/astrolabagency/opensanctions:latest 
          docker run ghcr.io/astrolabagency/opensanctions:latest 
          docker push ghcr.io/astrolabagency/opensanctions:latest 
      - name: login &pull images into portainer 
        run: |
         echo "${{ env.PORTAINER_REGISTRY_PASSWORD }}" | docker login --username "${{ env.PORTAINER_REGISTRY_USERNAME }}" --password-stdin portainer.astrolab-agency.com  
         docker  pull <ghcr.io/astrolabagency/opensanctions:latest>
         docker push  portainer.astrolab-agency.com/opensanctions:latest
